### ISSUE TITLE
Package doesn't work in WP-CLI 1.5.0

### ISSUE THREAD

**Issue by edpittol** [roborourke/wp-l10n-gen#2]
I updated my WP-CLI to 1.5.0 and the command exit without generate the PO file. So, I back to 1.4.1 and everything is ok.

**Comment by roborourke** [comment]
@edpittol I've made some updates recently and I have it working with WP CLI 2.0.0-alpha. Can you update the package and try again?

Also it might be worth checking out the official [WP CLI i18n command package](https://github.com/wp-cli/i18n-command) - it's likely this will be better maintained in the future. I'm going to contribute some of the features in this package back to that one.
